name: Build maven application

on:
  workflow_call:
    inputs:
      java_version:
        description: "Application java version"
        type: string
        required: true

steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: "zulu"
      java-version: "${{ inputs.java_version }}"
      architecture: x64
      cache: maven
  - run: mvn clean install -Dmaven.test.skip
