name: Build maven application

on:
  workflow_call:
    inputs:
      java_version:
        description: "Application java version"
        type: string
        required: true

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "${{ inputs.java_version }}"
          architecture: x64
          cache: maven
      - name: Build application
        run: mvn clean install
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/
