name: Create feature branch pull request

on:
  workflow_call:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Extract changes metadata
        id: change_metadata
        shell: bash
        run: |
          echo "feature_branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: create pull request
        run: |
          gh pr create \
          -B ${{ steps.change_metadata.outputs.feature_branch_name }} \
          -H ${{ github.event.repository.default_branch }} \
          --title '[FEAT] PR gerado automaticamente. ${{ steps.change_metadata.outputs.feature_branch_name }} -> ${{ github.event.repository.default_branch }}' \
          --body 'PR gerado automaticamente'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
