name: Deploy application to ECS cluster

on:
  workflow_call:
    inputs:
      application_name:
        description: "Application name"
        required: true
        type: string
      aws_region:
        description: "AWS region"
        required: true
        type: string
      iam_role:
        description: "IAM role to assume"
        required: true
        type: string
      environment:
        description: "Environment"
        required: true
        type: string
      cluster:
        description: "ECS cluster name"
        required: true
        type: string
      task_definition:
        description: "ECS task definition"
        required: true
        type: string
      docker_image_tag:
        description: "Docker image tag"
        required: true
        type: string

jobs:
  deploy-to-ecs:
    name: "[${{ inputs.environment }}] Deploy application to ECS cluster"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ inputs.iam_role }}"
          aws-region: "${{ inputs.aws_region }}"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Check if Docker image exists
        run: |
          if ! docker manifest inspect -v ${{ inputs.docker_image_tag }}; then
            echo "Docker image '${{ inputs.docker_image_tag }}' doesn't exists"
            exit 1
          fi
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: "${{ inputs.task_definition }}"
          container-name: "${{ inputs.application_name }}-${{ inputs.environment }}"
          image: "${{ inputs.docker_image_tag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: "${{ inputs.application_name }}-${{ inputs.environment }}"
          cluster: "${{ inputs.cluster }}"
          wait-for-service-stability: true