name: Quality Gate

on:
  workflow_call:
    inputs:
      application_name:
        description: "Application name"
        required: true
        type: string
      java_version:
        description: "Application java version"
        type: string
        required: true
      branch_name:
        description: "Branch name"
        type: string
        required: true
      sonar_wait_quality_gate:
        description: "If true the workflow will wait for the quality gate to finish"
        type: string
        required: true
      sonar_host:
        description: "SonarQube host"
        type: string
        required: true
    secrets:
      sonar_token:
        description: "SonarQube token"
        required: true

jobs:
  quality-gate:
    name: Apply quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "${{ inputs.java_version }}"
          architecture: x64
          cache: maven
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/
      - name: Run SonarQube analysis
        run: >
          mvn sonar:sonar
          -Dsonar.projectKey=${{ inputs.application_name }}
          -Dsonar.projectName=${{ inputs.application_name }}
          -Dsonar.host.url=${{ inputs.sonar_host }}
          -Dsonar.token=${{ secrets.sonar_token }}
          -Dsonar.branch.name=${{ inputs.branch_name }}
          -Dsonar.qualitygate.wait=${{ inputs.sonar_wait_quality_gate }}
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar