name: Run security analysis

on:
  workflow_call:
    secrets:
      snyk_token:
        description: 'Snyk token'
        required: true

jobs:
  snyk:
    name: Snyk analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
